FROM node:14-slim as node

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install --production

COPY . .

RUN yarn build



FROM nginx:1.20.0-alpine

WORKDIR /usr/share/nginx/html
COPY --from=node /usr/src/app/build .
