version: "3"

services:
  mongo:
    image: mongo:3.6.22-xenial
    restart: always
    expose:
      - "27017"
    networks:
      - mern-app
    volumes:
      - ./docker/mongo/data/db:/data/db

  api-server:
    image: api-server
    restart: always
    expose:
      - "5000"
    networks:
      - mern-app
    depends_on:
      - mongo

  react-app:
    image: react-app
    restart: always
    stdin_open: true
    expose:
      - "3000"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
